name: Terraform Apply
on: 
  workflow_dispatch: {}
  push:
    branches:
      - 'feature/action'
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_key_pub_project: ${{secrets.TF_VAR_AWS_KEY_PUB_PROJECT}}

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Apply
      run: |
        terraform init
        terraform apply